name: Build and Test

on:
  push:
    tags:
      - v0.*

jobs:
  builds:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        run: |
          npm i -g yarn
      - name: npm install, build, and test
        run: |
          yarn install
          yarn run build --if-present
          yarn test
          env:
            CI: true